model:
  name: 'MinkUNet34'
  in_feat_size: 1
  out_classes: 19

source_dataset:
  version: 'full'
  name: 'SynLiDAR'
  dataset_path: 'data/SynLiDAR'
  mapping_path: '_resources/synlidar_semantickitti.yaml'
  weights_path: '_weights/synlidar2semantickitti_correct.npy'
  target: null
  voxel_size: 0.05
  num_pts: 80000
  ignore_label: -1
  augment_data: false

target_dataset:
  version: 'full'
  name: 'SemanticKITTI'
  dataset_path: 'data/SemanticKITTI/data/sequences'
  mapping_path: '_resources/semantic-kitti.yaml'
  target: null
  voxel_size: 0.05
  num_pts: 80000
  ignore_label: -1
  augment_data: false

masked_dataset:
  augment_data: false
  augment_mask_data: false
  remove_overlap: false

pipeline:
  epochs: 5
  steps: null
  gpus: [0]
  precision: 32
  seed: 1234
  save_dir: 'experiments/cosmix/synlidar/semantickitti'

  dataloader:
    train_batch_size: 8
    val_batch_size: 8
    num_workers: 24

  optimizer:
    name: 'SGD'
    lr: 0.0008

  scheduler:
    name:

  lightning:
    check_val_every_n_epoch: 1
    clear_cache_int: 1
    resume_checkpoint: null
    val_check_interval: 1.0
    num_sanity_val_steps: 2

  wandb:
    run_name: 'SemanticKITTI'
    project_name: 'cosmix-uda'
    entity_name: 'liwanmeng'
    offline: true

adaptation:
  student_checkpoint: '/home/lichonger/AAAAA_DA_semantic_segmentation/ICRA_2025/cosmix-uda/experiments/pretrained/synlidar/semantickitti/pretrained_model.ckpt'
  teacher_checkpoint: '/home/lichonger/AAAAA_DA_semantic_segmentation/ICRA_2025/cosmix-uda/experiments/pretrained/synlidar/semantickitti/pretrained_model.ckpt'
  filtering: 'confidence'
  adaptive_weight: false
  oracle_rate: 0.0
  shuffle_batches: false
  compositional: false
  source_filtering: false
  propagation: false
  propagation_size: 0
  weighted_sampling: true
  self_paced: false
  is_mix3d: false
  is_mix3d_pseudo: false
  selection_perc: 1
  remove_class: null
  target_confidence_th: 0.0
  losses:
    source_criterion: 'CELoss'
    target_criterion: 'SoftDICELoss'
    other_criterion: null
    source_weight: 1.0
    target_weight: 1.0
    other_weight: 0.

  momentum:
    base_tau: 0.9
    final_tau: 0.9
    update_every: 500

